import type { ArchiveItem } from './types'

export const archiveItems: ArchiveItem[] = [
  {
    id: '1',
    title: 'Spirited Away',
    category: 'anime',
    year: 2001,
    status: 'completed',
    rating: 10,
    note: 'A timeless masterpiece. The world-building and animation are breathtaking. Watched multiple times.',
    imageUrl: 'https://images.unsplash.com/photo-1612036782180-69c773e01498?w=300&h=400&fit=crop',
    hours: 2,
  },
  {
    id: '2',
    title: 'My Neighbor Totoro',
    category: 'anime',
    year: 1988,
    status: 'completed',
    rating: 9,
    note: 'A heartwarming tale of childhood wonder and family bonds. Perfect for all ages.',
    imageUrl: 'https://images.unsplash.com/photo-1578926078328-123456789abc?w=300&h=400&fit=crop',
    hours: 1.5,
  },
  {
    id: '3',
    title: "Howl's Moving Castle",
    category: 'anime',
    year: 2004,
    status: 'completed',
    rating: 9,
    note: 'Stunning visual storytelling with memorable characters and a beautiful romance.',
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=300&h=400&fit=crop',
    hours: 1.8,
  },
  {
    id: '4',
    title: 'The Wind Rises',
    category: 'anime',
    year: 2013,
    status: 'completed',
    rating: 8,
    note: 'A poetic exploration of dreams and ambition. Beautiful craftsmanship throughout.',
    imageUrl: 'https://images.unsplash.com/photo-1537449191749-1a80c0a14f04?w=300&h=400&fit=crop',
    hours: 2.2,
  },
  {
    id: '5',
    title: 'Princess Mononoke',
    category: 'anime',
    year: 1997,
    status: 'completed',
    rating: 9,
    note: 'Epic environmental tale with complex characters. Visually stunning and thematically rich.',
    imageUrl: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=300&h=400&fit=crop',
    hours: 2.5,
  },
  {
    id: '6',
    title: 'Arriety',
    category: 'anime',
    year: 2010,
    status: 'completed',
    rating: 8,
    note: 'Charming adaptation about tiny people living in secret. Delightful visuals and gentle pacing.',
    imageUrl: 'https://images.unsplash.com/photo-1542696914-67a6e1cfb32b?w=300&h=400&fit=crop',
    hours: 1.4,
  },
  {
    id: '7',
    title: 'Berserk',
    category: 'manga',
    year: 1989,
    status: 'in-progress',
    rating: 9,
    note: 'Epic dark fantasy with incredible world-building. Currently on volume 30 of 40+.',
    imageUrl: 'https://images.unsplash.com/photo-1552890740-6b408dc2b2a0?w=300&h=400&fit=crop',
    chapters: 362,
  },
  {
    id: '8',
    title: 'Attack on Titan',
    category: 'manga',
    year: 2009,
    status: 'completed',
    rating: 8,
    note: 'Thrilling action series with great plot twists. Completed the entire manga run.',
    imageUrl: 'https://images.unsplash.com/photo-1545243424-2b36b4667173?w=300&h=400&fit=crop',
    chapters: 139,
  },
  {
    id: '9',
    title: 'Death Note',
    category: 'manga',
    year: 2003,
    status: 'completed',
    rating: 9,
    note: 'Psychological thriller that kept me on the edge. One of my favorite manga series ever.',
    imageUrl: 'https://images.unsplash.com/photo-1533439396036-7c42e40e9ff8?w=300&h=400&fit=crop',
    chapters: 108,
  },
  {
    id: '10',
    title: 'Elden Ring',
    category: 'games',
    year: 2022,
    status: 'completed',
    rating: 10,
    note: 'Revolutionary open-world souls-like. Best gaming experience of the year. Multiple playthroughs.',
    imageUrl: 'https://images.unsplash.com/photo-1535745675025-e9f53e5f5b9c?w=300&h=400&fit=crop',
    hours: 150,
  },
  {
    id: '11',
    title: 'The Legend of Zelda: Breath of the Wild',
    category: 'games',
    year: 2017,
    status: 'completed',
    rating: 9,
    note: 'Masterclass in game design. Freedom and creativity at every turn. A true landmark title.',
    imageUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=300&h=400&fit=crop',
    hours: 120,
  },
  {
    id: '12',
    title: 'Hollow Knight',
    category: 'games',
    year: 2017,
    status: 'completed',
    rating: 9,
    note: 'Beautifully challenging metroidvania. Atmospheric art style and haunting soundtrack.',
    imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=300&h=400&fit=crop',
    hours: 80,
  },
]
